definitions:
  req.Register:
    properties:
      nick_name:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - nick_name
    - password
    - username
    type: object
  resp.Register:
    properties:
      code:
        description: 返回码
        type: integer
      message:
        description: 返回信息
        type: object
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/e/get_e_page:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/req.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.Register'
        "400":
          description: 返回No Found
          schema:
            type: string
        "500":
          description: 返回internal error
          schema:
            type: string
      summary: 用户注册
      tags:
      - user
swagger: "2.0"
